inherit_from: rubocop-todo.yml

Documentation:
  Exclude:
    - "lib/cequel/version.rb"
    - "lib/cequel/errors.rb"
    - "lib/cequel/record/errors.rb"

HashSyntax:
  Exclude:
    - "lib/cequel/record/tasks.rb"

IfUnlessModifier:
  Enabled: false

LineLength:
  Exclude:
    - "lib/cequel/schema/column.rb"
    - "lib/cequel/record/record_set.rb"
    - "lib/cequel/record/properties.rb"
    - "lib/cequel/record/mass_assignment.rb"
    - "lib/cequel/record/collection.rb"
    - "lib/cequel/metal/updater.rb"
    - "lib/cequel/metal/deleter.rb"
    - "lib/cequel/metal/data_set.rb"
    - "lib/cequel/metal/batch.rb"
