<% app_name = Cequel::Record::Railtie.app_name -%>
development:
  host: '127.0.0.1'
  port: 9042
  keyspace: <%= app_name %>_development
  max-retries: 3

test:
  host: '127.0.0.1'
  port: 9042
  keyspace: <%= app_name %>_test
  max-retries: 3

production:
  hosts:
    - 'cass1.<%= app_name %>.biz'
    - 'cass2.<%= app_name %>.biz'
    - 'cass3.<%= app_name %>.biz'
  port: 9042
  keyspace: <%= app_name %>_production
  username: 'myappuser'
  password: 'password1'
  max-retries: 3
